# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170704_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagelink',
            name='link_image',
            field=models.ImageField(upload_to='static/site_images/homepage/'),
        ),
    ]
