# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_homepageskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageskills',
            name='custom_icon',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
