# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_homepageskills_custom_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_description', models.CharField(blank=True, max_length=250)),
                ('optional_icon', models.CharField(blank=True, max_length=30)),
                ('optional_class', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='homepageskills',
            name='optional_class',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepageskills',
            name='skill_group',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='homepage.HomepageSkillGroup'),
            preserve_default=False,
        ),
    ]
